/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RotacaoRouteImport } from './routes/rotacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as IndexRouteImport } from './routes/index'

const RotacaoRoute = RotacaoRouteImport.update({
  id: '/rotacao',
  path: '/rotacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/rotacao': typeof RotacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/rotacao': typeof RotacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/rotacao': typeof RotacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colaboradores' | '/configuracoes' | '/rotacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colaboradores' | '/configuracoes' | '/rotacao'
  id: '__root__' | '/' | '/colaboradores' | '/configuracoes' | '/rotacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  RotacaoRoute: typeof RotacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rotacao': {
      id: '/rotacao'
      path: '/rotacao'
      fullPath: '/rotacao'
      preLoaderRoute: typeof RotacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  RotacaoRoute: RotacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
